/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoyoRouteImport } from './routes/apoyo'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as SnacksRouteImport } from './routes/snacks'
import { Route as SosRouteImport } from './routes/sos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoRoute = ApoyoRouteImport.update({
  id: '/apoyo',
  path: '/apoyo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const SnacksRoute = SnacksRouteImport.update({
  id: '/snacks',
  path: '/snacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/diario': typeof DiarioRoute
  '/snacks': typeof SnacksRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/diario': typeof DiarioRoute
  '/snacks': typeof SnacksRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/diario': typeof DiarioRoute
  '/snacks': typeof SnacksRoute
  '/sos': typeof SosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apoyo' | '/diario' | '/snacks' | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apoyo' | '/diario' | '/snacks' | '/sos'
  id: '__root__' | '/' | '/apoyo' | '/diario' | '/snacks' | '/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoyoRoute: typeof ApoyoRoute
  DiarioRoute: typeof DiarioRoute
  SnacksRoute: typeof SnacksRoute
  SosRoute: typeof SosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo': {
      id: '/apoyo'
      path: '/apoyo'
      fullPath: '/apoyo'
      preLoaderRoute: typeof ApoyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snacks': {
      id: '/snacks'
      path: '/snacks'
      fullPath: '/snacks'
      preLoaderRoute: typeof SnacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoyoRoute: ApoyoRoute,
  DiarioRoute: DiarioRoute,
  SnacksRoute: SnacksRoute,
  SosRoute: SosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
